<a href="https://colab.research.google.com/github/Grlee316/PythonLearning/blob/main/NumpyIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY

like matlab but not a matlab

not made to replace matlab

ndarray

In [53]:
!apt-get install -y git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.


In [56]:
!git clone https://github.com/Grlee316/PythonLearning

fatal: destination path 'PythonLearning' already exists and is not an empty directory.


In [1]:
#numerical python
import numpy as np


In [2]:
v = np.array([1,2,3]) #creating an array by giving a container


In [5]:
v

array([1, 2, 3])

In [8]:
type(v)

numpy.ndarray

In [10]:
v.ndim #ndimension

1

In [13]:
v.shape #shape -> 3 collumns no rows (1 dimensions)

(3,)

In [15]:
v.size #how many elements in total

3

In [17]:
v.dtype

dtype('int64')

In [22]:
m = np.array(
    [[1,2,3],
     [4,5,6]]
)

In [24]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
print(m)

[[1 2 3]
 [4 5 6]]


In [27]:
m.shape

(2, 3)

In [38]:
m.ndim;

In [30]:
m.size

6

In [34]:
#tensors
t = np.array(
    [[[1,2,3],[1,2,3]],
    [[10,20,30],[40,50,60]
]])

In [35]:
t

array([[[ 1,  2,  3],
        [ 1,  2,  3]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [36]:
t.shape

(2, 2, 3)

In [37]:
t.ndim

3

In [41]:
# Placeholders
z = np.zeros([2,2,3])
z

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [51]:
# in Numpy, you cannot just append it

e = np.eye(5) #identity matriz
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
!git add .
!git commit -m "Commit message"
!git push origin main

fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
