<a href="https://colab.research.google.com/github/Grlee316/PythonLearning/blob/main/NumpyIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY

like matlab but not a matlab

not made to replace matlab

ndarray

In [ ]:
!apt-get install -y git

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.


In [ ]:
!git clone https://github.com/Grlee316/PythonLearning

fatal: destination path 'PythonLearning' already exists and is not an empty directory.


In [2]:
#numerical python
import numpy as np


In [ ]:
v = np.array([1,2,3]) #creating an array by giving a container


In [ ]:
v

array([1, 2, 3])

In [ ]:
type(v)

numpy.ndarray

In [ ]:
v.ndim #ndimension

1

In [ ]:
v.shape #shape -> 3 collumns no rows (1 dimensions)

(3,)

In [ ]:
v.size #how many elements in total

3

In [ ]:
v.dtype

dtype('int64')

In [ ]:
m = np.array(
    [[1,2,3],
     [4,5,6]]
)

In [ ]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
print(m)

[[1 2 3]
 [4 5 6]]


In [ ]:
m.shape

(2, 3)

In [ ]:
m.ndim;

In [ ]:
m.size

6

In [ ]:
#tensors
t = np.array(
    [[[1,2,3],[1,2,3]],
    [[10,20,30],[40,50,60]
]])

In [ ]:
t

array([[[ 1,  2,  3],
        [ 1,  2,  3]],

       [[10, 20, 30],
        [40, 50, 60]]])

In [ ]:
t.shape

(2, 2, 3)

In [ ]:
t.ndim

3

In [ ]:
# Placeholders
z = np.zeros([2,2,3])
z

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# in Numpy, you cannot just append it

e = np.eye(5) #identity matriz
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
ra = np.random.randn(3,4)
ra

array([[ 0.09739233,  0.02680859,  0.35937497,  1.03463145],
       [ 0.63990272,  0.17807057, -0.72963665,  1.42841893],
       [-0.8561266 , -1.87743861, -0.91320131, -0.71334101]])

In [ ]:
r = np.arange(10,20,0.5)
r

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [ ]:
r.shape #matrix of 20,0

(20,)

In [ ]:
rint = np.random.randint(5,10,(3,4))
rint

array([[7, 6, 6, 8],
       [8, 8, 6, 9],
       [7, 7, 9, 9]])

In [ ]:
np.logspace(-100,100,10)

array([1.00000000e-100, 1.66810054e-078, 2.78255940e-056, 4.64158883e-034,
       7.74263683e-012, 1.29154967e+011, 2.15443469e+033, 3.59381366e+055,
       5.99484250e+077, 1.00000000e+100])

In [4]:
np.logspace(-100,100)

array([1.00000000e-100, 1.20679264e-096, 1.45634848e-092, 1.75751062e-088,
       2.12095089e-084, 2.55954792e-080, 3.08884360e-076, 3.72759372e-072,
       4.49843267e-068, 5.42867544e-064, 6.55128557e-060, 7.90604321e-056,
       9.54095476e-052, 1.15139540e-047, 1.38949549e-043, 1.67683294e-039,
       2.02358965e-035, 2.44205309e-031, 2.94705170e-027, 3.55648031e-023,
       4.29193426e-019, 5.17947468e-015, 6.25055193e-011, 7.54312006e-007,
       9.10298178e-003, 1.09854114e+002, 1.32571137e+006, 1.59985872e+010,
       1.93069773e+014, 2.32995181e+018, 2.81176870e+022, 3.39322177e+026,
       4.09491506e+030, 4.94171336e+034, 5.96362332e+038, 7.19685673e+042,
       8.68511374e+046, 1.04811313e+051, 1.26485522e+055, 1.52641797e+059,
       1.84206997e+063, 2.22299648e+067, 2.68269580e+071, 3.23745754e+075,
       3.90693994e+079, 4.71486636e+083, 5.68986603e+087, 6.86648845e+091,
       8.28642773e+095, 1.00000000e+100])